version: "3"

services:
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: "trymee-tests"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "tm_tests"